# Generated by Django 5.0.1 on 2024-03-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100, unique=True)),
                ('admin_password', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_age', models.IntegerField()),
                ('emp_role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('req_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('emp_role', models.CharField(default=None, max_length=100)),
                ('emp_count', models.IntegerField(default=None)),
                ('client_name', models.CharField(max_length=100)),
                ('client_password', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='AEC.admin')),
                ('employee_list', models.ManyToManyField(default=None, to='AEC.employee')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='client_request',
            field=models.ManyToManyField(default=None, to='AEC.client'),
        ),
        migrations.AddField(
            model_name='admin',
            name='employee_list',
            field=models.ManyToManyField(default=None, to='AEC.employee'),
        ),
    ]
