# Generated by Django 5.0.1 on 2024-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0002_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
