# Generated by Django 5.0.1 on 2024-03-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0003_alter_client_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='emp_role',
        ),
    ]
