# Generated by Django 5.0.1 on 2024-03-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0004_remove_client_emp_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emp_role',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
