# Generated by Django 5.0.1 on 2024-03-24 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0005_client_emp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AEC.admin'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='emp_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='emp_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='employee_list',
            field=models.ManyToManyField(to='AEC.employee'),
        ),
        migrations.AlterField(
            model_name='client',
            name='req_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
