# Generated by Django 5.0.1 on 2024-03-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0008_alter_client_admin_id_alter_client_client_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='req_id',
            new_name='client_id',
        ),
    ]
