# Generated by Django 5.0.1 on 2024-04-01 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0010_rename_client_id_client_req_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='req_id',
            new_name='request_id',
        ),
        migrations.CreateModel(
            name='admin_status',
            fields=[
                ('admin_status_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AEC.admin')),
                ('rejected_employee', models.ManyToManyField(related_name='client_rejected_employee', to='AEC.employee')),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AEC.client')),
                ('selected_employee', models.ManyToManyField(related_name='client_selected_employee', to='AEC.employee')),
            ],
        ),
        migrations.CreateModel(
            name='client_status',
            fields=[
                ('client_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AEC.admin')),
                ('rejected_employee', models.ManyToManyField(related_name='rejected_employee', to='AEC.employee')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AEC.client')),
                ('selected_employee', models.ManyToManyField(related_name='selected_employee', to='AEC.employee')),
            ],
        ),
    ]
