# Generated by Django 5.0.1 on 2024-04-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AEC', '0011_rename_req_id_client_request_id_admin_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_status',
            old_name='req_id',
            new_name='request_id',
        ),
    ]
